---
title: "Projects"
---

## Selected Projects

### Master's thesis - Auditory attention decoding (EEG & Audio)
- Finetuned [LaBraM](https://arxiv.org/abs/2405.18765) and [CLAP](https://arxiv.org/abs/2211.06687) to classify the attended speaker using a clinical dataset
- Implemented an audio-disjoint data splitting method to ensure no data leakage across clinical trials and subjects

[Thesis presentation](static/thesis_slides.pdf)


### News Media Community Detection
- Created a graph consisting of journalists
- Classical NLP methods
- Graph analysis & statistics

[View project](projects/community_detection/community_detection.qmd)

### 🥈 Danish National Championship in AI (2021)
- Collected data and trained models
- Deployed models to Azure exposed as FastAPI endpoints
- Object detection with YOLO
- NLP Movie rating prediction

### Classification of Sustainable Development Goals in academic literature
- Achieved SOTA performance at the time of development
- Collected data for training with the Twitter(X) API
- Deployed solution with a light HTML/CSS frontend
- Inference on articles from Scopus

---
